package com.eucalyptus.webui.shared.config;

public enum EnumService {
	ACCOUNT_SRV,
	GROUP_SRV,
	GROUP_ADDING_SRV,
	GROUP_DETAIL_SRV,
	USER_SRV,
	USER_APP_SRV,
	USER_APP_ADDING_SRV,
	CERT_SRV,
	POLICY_SRV,
	KEY_SRV,
	KEYPAIR_SRV,
	CPU_STAT_SRV,
	INSTANCE_SRV,
}
